language: python
sudo: required
cache: pip
env:
  MIN_PYLINT_SCORE: 8
  WITH_INTEGRATION: 1
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev --skip-lock
  - pipenv run python -m tests.run_app_tests
  - pipenv run nose2 --with-coverage
after_success:
  - coveralls
  - ./tests/docstyle.sh
  - if [ -z "$TRAVIS_TAG" ]; then
      echo "Not a tagged commit; skipping deploy.";
    else
      docker build ./ -t arxiv/submission-ui:${TRAVIS_TAG};
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker push arxiv/submission-ui:${TRAVIS_TAG});
    fi
